### ISSUE TITLE
Elixir script - Mix.Config.LoadError) could not load config ../../config/config.exs

### ISSUE THREAD

**Issue by williamweckl** [codeship/scripts#140]
Error when using Elixir script:

```
** (Mix.Config.LoadError) could not load config ../../config/config.exs
** (File.Error) could not read file "../../config/config.exs": no such file or directory
(elixir) lib/file.ex:244: File.read!/1
(mix) lib/mix/config.ex:180: Mix.Config.read!/2
(mix) lib/mix/tasks/loadconfig.ex:36: Mix.Tasks.Loadconfig.load/1
(mix) lib/mix/tasks/loadconfig.ex:27: Mix.Tasks.Loadconfig.run/1
(mix) lib/mix/task.ex:294: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:57: Mix.CLI.run_task/2
```

**Comment by williamweckl** [comment]
My mistake, was a problem with my umbrella project.
